### ISSUE TITLE
Update rubycritic/reek version

### ISSUE THREAD

**Issue by kowal** [polishgeeks/polishgeeks-dev-tools#17]
With polishgeeks-dev-tools 1.1.2, we're getting:
```
Yard                                     OK
ExamplesComparator                       OK
/.rvm/gems/ruby-2.2.2@adwords_api/gems/reek-1.6.3/lib/reek/smells/nested_iterators.rb:73:in `ignored_iterator?': undefined method `method_name' for (zsuper):#<Class:0x007fbefce1bf78> (NoMethodError)
	
from /.rvm/gems/ruby-2.2.2@adwords_api/gems/reek-1.6.3/lib/reek/smells/nested_iterators.rb:65:in `find_iters_for_iter_node'
from /.rvm/gems/ruby-2.2.2@adwords_api/gems/reek-1.6.3/lib/reek/smells/nested_iterators.rb:60:in `block in find_iters'
```

Probably caused by https://github.com/whitesmith/rubycritic/issues/45.

**Comment by nijikon** [comment]
They did not released a new version since they fix this issue. I will ping them if they can do that. We can upgrade it then.
